// Regenerates theme/icons.css: base64-embedded, subsetted Font Awesome fonts
// limited to the glyphs this theme actually uses, plus the minimal FA CSS
// (base classes + ::before content rules). Run with: bun run build:icons
//
// The output is committed, so runtime rendering has zero network dependency
// and no runtime dependency on @fortawesome packages.
const fs = require('fs');
const path = require('path');
const subsetFont = require('subset-font');

const FA_PKG = path.dirname(
  require.resolve('@fortawesome/fontawesome-free/package.json')
);

// Icons referenced by the theme partials and style.css.
const SOLID = ['up-right-from-square', 'location-dot', 'mobile-screen-button'];
const REGULAR = ['envelope'];
// Keep in sync with the "Social Media Brand Colors" block in style.css.
const BRANDS = [
  'linkedin', 'github', 'tumblr', 'foursquare', 'facebook', 'pinterest',
  'dribbble', 'instagram', 'twitter', 'soundcloud', 'wordpress', 'youtube',
  'stack-overflow', 'flickr', 'reddit', 'hacker-news', 'telegram',
];

const metadata = JSON.parse(
  fs.readFileSync(path.join(FA_PKG, 'metadata/icon-families.json'), 'utf8')
);

const glyph = (name, style) => {
  const icon = metadata[name];
  if (!icon) {
    throw new Error(`Unknown Font Awesome icon: ${name}`);
  }
  const freeStyles = (icon.familyStylesByLicense?.free || []).map(s => s.style);
  if (!freeStyles.includes(style)) {
    throw new Error(`Icon ${name} has no free "${style}" style (has: ${freeStyles})`);
  }
  return icon.unicode;
};

const subset = async (fontFile, names, style, family, weight) => {
  const unicodes = names.map(name => glyph(name, style));
  const text = unicodes
    .map(hex => String.fromCodePoint(parseInt(hex, 16)))
    .join('');
  const source = fs.readFileSync(path.join(FA_PKG, 'webfonts', fontFile));
  const woff2 = await subsetFont(source, text, { targetFormat: 'woff2' });
  return { family, weight, woff2, glyphs: names.map((name, i) => ({ name, unicode: unicodes[i] })) };
};

(async () => {
  const fonts = [
    await subset('fa-solid-900.woff2', SOLID, 'solid', 'Font Awesome 6 Free', 900),
    await subset('fa-regular-400.woff2', REGULAR, 'regular', 'Font Awesome 6 Free', 400),
    await subset('fa-brands-400.woff2', BRANDS, 'brands', 'Font Awesome 6 Brands', 400),
  ];

  let css = [
    '/* Font Awesome 6 Free subsets — generated by scripts/build-icons.js. DO NOT EDIT.',
    '   Source: @fortawesome/fontawesome-free (icons: CC BY 4.0, fonts: SIL OFL 1.1). */',
    '',
  ].join('\n');

  for (const { family, weight, woff2 } of fonts) {
    css += `@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url(data:font/woff2;base64,${woff2.toString('base64')}) format('woff2');
}
`;
  }

  css += `
.fa,
.fa-solid,
.fa-regular,
.fa-brands {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  display: inline-block;
  font-style: normal;
  font-variant: normal;
  text-rendering: auto;
  line-height: 1;
}
.fa-solid {
  font-family: 'Font Awesome 6 Free';
  font-weight: 900;
}
.fa-regular {
  font-family: 'Font Awesome 6 Free';
  font-weight: 400;
}
.fa-brands {
  font-family: 'Font Awesome 6 Brands';
  font-weight: 400;
}
`;

  for (const { glyphs } of fonts) {
    for (const { name, unicode } of glyphs) {
      css += `.fa-${name}::before { content: '\\${unicode}'; }\n`;
    }
  }

  fs.writeFileSync(path.join(__dirname, '..', 'theme', 'icons.css'), css);
  console.log('theme/icons.css written (', css.length, 'bytes )');
})();
